config/routes.rb
Rails.application.routes.draw do
 
  resources :contents
  
  resources :courses
  
  root to: 'sessions#new'
  
  get 'welcome/homepage'

  resources :users
 
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :contents
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates 	:email, presence: true, length: { maximum: 255},
				format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.includes(:course).all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new

    render locals: { courses: Course.all}
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.includes(:course).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:unit_One, :unit_Two, :unit_Three, :unit_Four, :unit_Five, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.includes(:contents).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :price, :info)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
    		log_in user
    		redirect_to welcome_homepage_url
    else
    		flash.now[:danger] = 'Invalid credentials.'
    		render 'new'
    end
  end

  def destroy
  	log_out
  	redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def authenticate_user
      if !logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/views/contents/_form.html.erb
<% if logged_in? %>

<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.collection_select(:course_id, Course.all, :id, :name) %>
  </div>
  
  <div class="field">
    <%= f.label :unit_One %>
    <%= f.text_field :unit_One %>
  </div>

  <div class="field">
    <%= f.label :unit_Two %>
    <%= f.text_field :unit_Two %>
  </div>

  <div class="field">
    <%= f.label :unit_Three %>
    <%= f.text_field :unit_Three %>
  </div>

  <div class="field">
    <%= f.label :unit_Four %>
    <%= f.text_field :unit_Four %>
  </div>

  <div class="field">
    <%= f.label :unit_Five %>
    <%= f.text_field :unit_Five %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1"></div>
  </div>
  <% if logged_in? %>
  
  <h1>Contents</h1>
  <table class = "table">
    <thead>
      <tr>
        <th>Course</th>
        <th>Unit one</th>
        <th>Unit two</th>
        <th>Unit three</th>
        <th>Unit four</th>
        <th>Unit five</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contents.each do |content| %>
        <tr>
          <td><%= content.course.name %></td>
          <td><%= content.unit_One %></td>
          <td><%= content.unit_Two %></td>
          <td><%= content.unit_Three %></td>
          <td><%= content.unit_Four %></td>
          <td><%= content.unit_Five %></td>
          <td><%= link_to 'Show', content %></td>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Content', new_content_path %>
  </div>
  <br>
  <% else %>
      <%= link_to "Log in", login_path %>
  <% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<% if logged_in? %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @content.course.name %>
</p>

<p>
  <strong>Unit one:</strong>
  <%= @content.unit_One %>
</p>

<p>
  <strong>Unit two:</strong>
  <%= @content.unit_Two%>
</p>

<p>
  <strong>Unit three:</strong>
  <%= @content.unit_Three %>
</p>

<p>
  <strong>Unit four:</strong>
  <%= @content.unit_Four %>
</p>

<p>
  <strong>Unit five:</strong>
  <%= @content.unit_Five %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/courses/_form.html.erb
<% if logged_in? %>

<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else %>
    <%= link_to "Log in", login_path %>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>


  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8"></div>
      <div class="col-md-4"></div>
      </div>
<% if logged_in? %>
      <h1>Courses</h1>
  <table class = "table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Info</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= course.price %></td>
          <td><%= course.info %></td>
          <td><%= link_to 'Show', course %></td>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Course', new_course_path %>

  </div>
 
  <% else %>
  <%= link_to "Log in", login_path %>
  <% end %> 

  <br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<% if logged_in? %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<p>
  <strong>Info:</strong>
  <%= @course.info %>
</p>

<p>
  <strong>Units:</strong>
      <% if !@course.contents.blank? %>
          <% @course.contents.each do  |c| %>
            <%= c.unit_One %>
            <%= c.unit_Two %>
            <%= c.unit_Three %>
            <%= c.unit_Four %>
            <%= c.unit_Five %>
          <%end%>
        <%end%>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <% if logged_in? %>
      <header class="navbar navbar-fixed-top navbar-inverse">
        
          <% link_to "sample app", '#', id: "logo" %>
            <nav>
              <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "Homepage", welcome_homepage_path %></li>
                
                <li><%= link_to "Courses", courses_path %></li>

                <li><%= link_to "Units", contents_path %></li>

                <li><%= link_to "Users", users_path %></li>

              	<li><%= link_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </nav>
        </header> 
      <div class="container-fluid">
          <div class="row">
          <div class="col-md-8 col-md-offset-2"></div>
          </div>
        <div class="page-header">
        <h1>Welcome <%= current_user.name %>!</h1>
        </div>
      </div>
    <% else %>
    	<%# link_to "Log in", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if logged_in? %>

<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

    <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<% else %>
    <%= link_to "Log in", login_path %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4"></div>
    </div>
<% if logged_in? %>
  <h1>Users</h1>

  <table class = "table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Password digest</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.password_digest %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New User', new_user_path %>
  </div>
  <% else %>
    <%= link_to "Log in", login_path %>
  <% end %>
<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if logged_in? %>
s
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/welcome/homepage.html.erb
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4"></div>
    </div>

 <% if logged_in? %>

	<p> <strong>to the Course Information Thing!!</strong></p>
	<div id='nekojo'>
	<%= image_tag 'nekojo.jpg' %>
	</div>

<% else %>
<% end %>

</body>